version: "3.2"
services:
  docs:
    image: ghcr.io/codex-team/codex.docs:v2.2.3
    ports:
      - "13000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./db:/usr/src/app/db
      - ./docs-config.yaml:/usr/src/app/docs-config.yaml
