version: "3.2"
services:
  docs:
    image: versadesk/codexdocx:2.2.3
    user: 1000 #should be 1000 (You need to rebuild image before change it)
    ports:
      - "80:80"
    environment:
      - URL_prefix=/result/test/proxy # /proxy must add in the end.
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./db:/usr/src/app/db
      - ./docs-config.yaml:/usr/src/app/docs-config.yaml
